server:
  port: 8081

# pxe服务器的信息
itennis:
  pxeServer:
    ip: 10.9.9.99
    netmask: 255.0.0.0
    user: root
    password: 1234
    interface: ens33
    os: centos
    version: 7
    iso: /opt/rhel-server-7.3-x86_64-dvd.iso

  # pxe安装的操作系统信息
  installOS:
    os: centos
    version: 7
    password: 123456
    iso: /opt/rhel-server-7.3-x86_64-dvd.iso
    driver:

  # pxe安装的操作系统的分区
  partitions:
    - {path: /,fstype: ext4,size: 20480,ondisk: sda}
    - {path: /tmp,fstype: ext4,size: 10240,ondisk: sda}
    - {path: /var,fstype: ext4,size: 10240,ondisk: sda}
    - {path: /var/log,fstype: ext4,size: 153600,ondisk: sda}
    - {path: /srv/BigData,fstype: ext4,size: 61440,ondisk: sda}
    - {path: /opt,fstype: ext4,size: 1,ondisk: sda}

  # DHCP服务器的信息
  dhcpServer:
    ip: 10.9.9.99
    netmask: 255.0.0.0
    interface: ens34
    subnet: 10.0.0.0
    start: 10.9.9.100
    end: 10.9.9.200

  # 系统需要安装的软件包
  packages:
    - tftp-server
    - dhcp
    - xinetd
    - httpd
    - redhat-lsb
    - expect
    - syslinux
    - tree
    - vsftpd
    - ipmitool
    - expect

# 用来刷新配置
management:
  endpoints:
    web:
      exposure:
        include: env,refresh

# 用来配置日志级别
logging:
  level:
    com.itennishy.lops.executor.JSchExecutor: warn
    com.itennishy.lops: info
  file:
    path: logs/
    name: itennis.log
    max-size: 1GB
    max-history: 7