server:
  port: 8088

# pxe服务器的信息
itennis:
  pxeServer:
    ip: 192.168.0.199
    netmask: 255.255.255.0
    user: root
    password: 123456
    interface: ens33
    os: redhat
    version: 7.3
    iso: /opt/rhel-server-7.3-x86_64-dvd.iso

  # pxe安装的操作系统信息
  installOS:
    os: redhat
    version: 7.3
    password: 123456
    interface: ens33
    iso: /opt/rhel-server-7.3-x86_64-dvd.iso
    driver:

  # pxe安装的操作系统的分区
  partitions:
    - {path: /,fstype: ext4,size: 20480,ondisk: sda}
    - {path: /tmp,fstype: ext4,size: 10240,ondisk: sda}
    - {path: /var,fstype: ext4,size: 10240,ondisk: sda}
    - {path: /var/log,fstype: ext4,size: 153600,ondisk: sda}
    - {path: /srv/BigData,fstype: ext4,size: 61440,ondisk: sda}
    - {path: /opt,fstype: ext4,size: 1,ondisk: sda}

  # DHCP服务器的信息
  dhcpServer:
    ip: 192.168.0.199
    netmask: 255.255.255.0
    subnet: 192.168.0.0
    start: 192.168.0.100
    end: 192.168.0.200

  # 系统需要安装的软件包
  packages:
    - tftp-server
    - dhcp
    - xinetd
    - httpd
    - redhat-lsb
    - expect
    - syslinux
    - tree
    - vsftpd
    - ipmitool
    - expect

# 用来刷新配置
management:
  endpoints:
    web:
      exposure:
        include: env,refresh

# 用来配置日志级别
logging:
  level:
    com.itennishy.lops.executor.JSchExecutor: info
    com.itennishy.lops: info
  file: logs/itennis.log